#%%
# Action Space
ACTION_GO_LEFT = 0
ACTION_GO_RIGHT = 1
ACTION_GO_STRAIGHT = 2
ACTION_STOP = 3
N_ACTIONS = 4

# EGO 
EGO_LENGTH = 5.0 #m
EGO_WIDTH = 2.0 #m

SMALLEST_TTC_ALLOWED = 2.0 #sec

#%% Monte Carlo Tree Search Constants
UCB_C = 1e-1
DISCOUNT_FACTOR = 0.4
N_MIN_NODE_VISITS = 2
EXPANSION_UPDATE_N_CYCLE = 2
MAX_SEARCH_ITERATIONS = N_ACTIONS

